<?php

/**
 * Add the modules listed below and then uncomment.
 *
 */  

$config = array(
    'admin_toolbar',
    'admin_toolbar_tools',
    'admin_toolbar_content_languages',
    'adminimal_admin_toolbar',
    'bootstrap',
    'content_translation',
    'ctools',
    'devel',
    'imagemagick',
    'kint',
    'language',
    'module_filter',
    'pathauto',
    'redirect',
    'stage_file_proxy',
    'token',
    'update'
 );
