#!/bin/bash

# Fixes the perms across a whole site.
# Relies on you being in the sereno/script directory, to check you don't run
# it somewhere dangerous.
# eg of usage:- #>d7-fix-perms

PARENT_DIRECTORY="${PWD}"

echo "checking $PARENT_DIRECTORY contains 'sereno/script'..."

if [[ $PARENT_DIRECTORY == *"sereno/script"* ]]; then
  # go to the site root
  cd ../../../

  echo "updating permissions for Drupal 8 in $PARENT_DIRECTORY ..."

  sudo chown rtatham:srn-web-owner . -R
  sudo chmod 755 . -R

  sudo chgrp apache-go ./config/* -R
  sudo chmod 775 ./config/* -R

  sudo chgrp apache-go ./web/sites/default/* -R
  sudo chmod 775 ./web/sites/default/* -R

  sudo chown rtatham:srn-web-owner ./web/sites/default/bax -R
  sudo chmod 755 ./web/sites/default/bax -R

  sudo chown rtatham:srn-web-owner ./web/sites/default/*.yml -R
  sudo chmod 755 ./web/sites/default/*.yml -R

  sudo chown rtatham:srn-web-owner ./web/sites/default/*settings* -R
  sudo chmod 444 ./web/sites/default/settings* -R

  sudo find . -type d -exec sudo chmod g+s {} \; # NB - there's a space after the curly braces

  echo "updated permissions for Drupal 8 in $PARENT_DIRECTORY"
else
  echo 'NOT DOING ANYTHING. You need to run this from within a dir called sereno/script'
fi
